### Build Configuration
You can find the source for the targets in the `Rakefile`, or by running `rake -T`.  The best way to customize
your build is to modify the first section of the Rakfile.

### Dependencies
- `clang` >= 3.4
- `ld`
- `xorriso`
- `yasm`
- `grub2`
- `rake`

### Linux
Building on Linux is quite simple, all you need to do is clone the repo at `https://github.com/joshbeitler/mirus` and
take care of the dependencies (commands provided below), depending on your distro.

**Fedora**
```
# yum install yasm clang xorriso
```

**Debian/Ubuntu**
```
# apt-get install yasm clang xorriso
```

### OSX
With a bit of simple fanangaling, Mirus will build natively on OSX as well.  You will need to make sure you enter
Xcode's settings and install the command line tools.

```
# brew install yasm xorriso
```

### Vagrant
Mirus is all hooked up to build on the wonderful [Vagrant](http://vagrantup.com).  We like to use a Fedora box, as
it most similarly mirrors what I use to develop normally.

```
$ vagrant up
$ vagrant ssh
$ cd /vagrant
$ rake
```

### Build Targets
The following targets are avalible via `rake <target-name>`:
- `default` - The default target, run when no arguments are provided
- `travis` - Special target for CI services; does not generate a disk image
- `clean` - Removes any files generated by the build system
- `qemu`- Run the resulting disk image in Qemu
