# dependencies
require 'colorize'

# define various targets
target          = "mirus"
iso_target      = target << ".iso"
bin_target      = target << ".bin"

# source files
cpp_files       = FileList['source/kernel/*.cpp', 'source/system/*.cpp', 'source/*.cpp']
header_files    = FileList['source/include/*.hpp', 'source/library/*.hpp']
asm_files       = FileList['source/asm/*.asm']

# object files
object_files    = cpp_files.sub(/\.cpp$/, '.o')
object_files    = object_files << asm_files.sub(/\.asm$/, '.o')

# .d files generated by clang
dep_files       = cpp_files.sub(/\.cpp$/, '.d')

# clang + additional options
compiler        = "clang++"
warnings        = "-Wall -Wextra -Wno-unused-parameter "
options         = "-fno-builtin -fno-exceptions -ffreestanding -std=c++11 -m32 -O0 "
include_paths   = "-Isource/include -Isource/library"
cpp_flags       = warnings << options << include_paths

# nasm + options
assembler       = "yasm"
assembler_flags = "-f elf"

# virtual machine options
vm              = "qemu-system-i386"
vm_flags        = "-serial file:/tmp/mirus_debug.log"

# create a directory to hold output
directory "build"

# stfu rake
verbose false

# compile
desc "Build all components"
task :build_all => ['build_asm', 'build_kernel'] do
    # ...
end

# build kernel
desc "Build the kernel"
task :build_kernel do
    cpp_files.each do |s|
        # replace .cpp with .o
        object_file = s.sub(/\.cpp$/, '.o')
        
        # compile + get status
        sh "#{compiler} #{cpp_flags} -MMD -MP -c #{s} -o #{object_file}" do |ok, res|
            if ! ok
                puts "[rake] Could not build #{s}".red
                puts "\t#{res}.exitstatus".red
            else
                puts "[rake] #{s} -> #{object_file}".green
            end
        end
    end
end

# build assembly
desc "Build bootstrap + lower level ASM code"
task :build_asm do
    asm_files.each do |t|
        # replace .asm with .o
        object_file = t.sub(/\.asm$/, '.o')
        
        # assemble + get status
        sh "#{assembler} #{assembler_flags} -o #{object_file} #{t}" do |ok, res|
            if ! ok
                puts "[rake] Could not build #{t}".red
                puts "\t#{res}.exitstatus".red
            else
                puts "[rake] #{t} -> #{object_file}".green
            end
        end
    end
end

# generate a bootable iso image of Mirus
desc "Creates bootable media"
task :make_iso => ['build_asm', 'build_kernel'] do
    puts "[rake] Generating ISO".blue
end

# clean object files, etc.
desc "Clean up all the extra crap"
task :clean do
    sh "rm -f #{object_files}"
    sh "rm -f #{dep_files}"
end

# start qemu
desc "Start QEMU with Mirus"
task :qemu do
    sh "#{vm} #{vm_flags} build/mirus.iso"
end

# default task
task :default => ['make_iso']
