# Copyright 2013 Joshua Beitler

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

# http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

verbose false

cpp_files = FileList['source/**/*.cpp']
cpp_flags = "-Wextra -std=c++11 -I source/include"
compiler  = "clang++"

task :default do
    cpp_files.each do |s|
        # compile + get status
        sh "#{compiler} #{cpp_flags} -o man #{cpp_files}"
    end
end

task :clean do
    sh "rm source/*.o"
    sh "rm man"
end